name: PNPM CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04  # 使用更新的 Ubuntu 版本
    defaults:
      run:
        shell: bash

    steps:
    # 1. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史记录

    # 2. 安装指定版本的 pnpm
    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 8.14.0
        run_install: false

    # 3. 设置 Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    # 4. 配置 pnpm 存储路径
    - name: Configure pnpm store
      run: |
        # 手动设置 pnpm store 路径
        mkdir -p ~/.pnpm-store
        pnpm config set store-dir ~/.pnpm-store
        
        # 验证配置
        echo "PNPM store path: $(pnpm store path)"
        echo "PNPM version: $(pnpm --version)"

    # 5. 安装依赖（带缓存）
    - name: Cache pnpm dependencies
      uses: actions/cache@v3
      id: pnpm-cache
      with:
        path: |
          ~/.pnpm-store
          node_modules
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

    # 6. 安装依赖
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      env:
        CI: true

    # 7. 后续步骤
    - name: Run linting
      run: pnpm run lint

    - name: Run tests
      run: pnpm run test
      env:
        CI: true

    - name: Build project
      run: pnpm run build
      env:
        NODE_ENV: production

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist