name: CI/CD Pipeline       # 工作流名称

on:                       # 触发条件
  push:
    branches: [ main ]    # 监听 main 分支的 push 事件

jobs:                     # 定义任务
  build-and-deploy:       # 任务 ID（自定义）
    runs-on: ubuntu-latest # 在 GitHub 提供的 Ubuntu 虚拟机运行

    steps:                # 任务步骤
    # 1. 拉取代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20  # 指定 Node 版本

    # 3. 安装依赖（利用缓存加速）
    - name: Install Dependencies
      run: npm ci         # 比 npm install 更严格，适合 CI
      env:
        CI: true          # 防止某些包执行非必要脚本

    # 4. 运行代码检查（可选）
    - name: Run Linter
      run: npm run lint   # 假设 package.json 中有 "lint": "eslint ."

    # 5. 运行测试（可选）
    - name: Run Tests
      run: npm test

    # 6. 构建生产包
    - name: Build Project
      run: npm run build  # 生成静态文件到 build/ 目录

    # 7. 部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # 第三方部署 Action
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # 自动注入的 token
        publish_dir: ./build              # 构建产物目录